# 内容所在的子目录，将显示在首页和归档页
mainSections = ["post"]
# 在 RSS 中输出全文
rssFullContent = true
favicon        = "img/favicon.jpg"

# 排序方式: "default", "lastmod"
SortBy              = "default"

[footer]
    customText = "© 2026 Milk_Dragon"

[dateFormat]
    # 使用当地日期格式
    published   = ":date_medium"
    lastUpdated = ":date_medium"

[sidebar]
    emoji    = "🚀"
    subtitle = "我是奶龙"
    avatar   = "img/avatar.jpg"

[article]
    headingAnchor = true
    math          = true
    readingTime   = true

    [article.license]
        enabled = true
        default = "采用 CC BY-NC-SA 4.0 许可协议"
